import Head from 'next/head'
import { initializeApollo, addApolloState } from '../apollo'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ARTICLES from '../graphql/queries/articles'

const Home = ({ articles }) => {
  console.log('articleData', articles)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Boilerplate for Nextjs, Apollo, Styled Components, and Strapi
        </h1>

        {articles?.map(({ attributes: { title, content, previewImage } }) => (
          <>
            <h2>{title}</h2>
            <Image src={`${process.env.API_URL}${previewImage?.data?.attributes?.url}`} alt="Test Image" width={96} height={144} />
            <div>{content}</div>
          </>
        ))}
      </main>
    </div>
  )
}

export async function getStaticProps() {
    const apolloClient = initializeApollo()
  
    const [ articleData ] = await Promise.all([
      apolloClient.query({ query: ARTICLES }),
    ])
  
    return addApolloState(apolloClient, {
      props: {
        articles: articleData?.data?.articles?.data
      },
      revalidate: 1,
    })
  }
  

export default Home;